In [23]:
import pandas as pd

In [24]:
# Load data
df=pd.read_excel('../Sales/sales_raw_500.xlsx')
df

     Order_ID Order_Date Customer Region  Product  Sales   Cost
0        1001 2023-01-13    Rohit  South   Mobile  23289  19118
1        1002 2023-10-07     Aman   West   Laptop   8905   5593
2        1003 2023-11-05    Rahul  South  Monitor  59987  39959
3        1004 2024-02-19    Rahul  South  Printer  49597  33892
4        1005 2024-01-26   Anjali  North   Laptop  54797  34468
5        1006 2023-11-06    Rohit  North  Printer  75284  47989
6        1007 2023-02-10   Suresh   East  Monitor  52400  40515
7        1008 2023-01-24    Priya   East   Laptop  35512  30538
8        1009 2023-08-21   Anjali  South   Tablet  51566  34180
9        1010 2023-12-16     Aman  South  Monitor  37087  24070
10       1011 2023-11-24   Suresh  South   Tablet  12331   8245
11       1012        NaT   Anjali   West   Tablet  13675   9070
12       1013 2024-03-24   Anjali  South  Printer  56856  49203
13       1014 2023-03-15    Rohit  South   Mobile  78579  59853
14       1015 2023-08-08    Kiran   West   Tablet  33746  30344
15       1016 2023-09-10     Aman  North   Laptop  25033  19731
16       1017 2023-08-05    Kiran  North  Printer  55019  42846
17       1018 2023-05-09   Suresh  North   Laptop  75381  62209
18       1019 2023-06-24     Aman   East  Printer  25730  18940
19       1020 2024-03-24    Rohit  South  Monitor  18947  16316
20       1021 2023-11-24   Suresh  South   Mobile  54009  44760
21       1022 2024-02-03   Suresh  North  Monitor  47487  35452
22       1023 2023-07-05    Rohit  South   Laptop  36571  31575
23       1024 2023-02-13    Pooja  North  Monitor  21483  13717
24       1025 2023-10-09     Neha   East  Monitor  60461  53768
25       1026 2024-01-22    Priya   East  Printer  53944  39456
26       1027 2023-03-03    Priya  South   Laptop  49313  29898
27       1028 2023-10-29    Priya  North   Laptop  12716   8502
28       1029 2024-03-16   Anjali  North  Monitor  36195  24740
29       1030 2023-10-04     Neha   West   Mobile  66993  56424
30       1031 2023-02-19    Vikas   East  Printer  58883  43579
31       1032 2023-12-11     Aman  North  Printer  49473  41566
32       1033 2023-04-09    Priya   West   Mobile  60296  39496
33       1034 2024-03-23     Aman   West  Monitor  17833  10970
34       1035 2024-03-04    Rahul  North   Mobile  26798  19346
35       1036 2024-03-18    Vikas  North   Mobile  54672  32838
36       1037 2024-02-06    Pooja   East  Printer  77845  62164
37       1038 2023-04-08    Rohit  South   Laptop  76066  47030
38       1039 2023-01-26    Kiran   West  Monitor  74615  48293
39       1040 2023-02-11     Neha  North  Monitor  13907  11161
40       1041 2023-03-03    Kiran  South  Monitor  10209   8022
41       1042 2023-10-26    Kiran   East   Tablet  31772  25446
42       1043 2023-05-16    Vikas  South   Tablet  64929  45116
43       1044 2023-02-07    Rahul   West  Monitor  78792  70820
44       1045 2023-04-20   Suresh   East   Mobile  50745  43856
45       1046 2023-07-09    Rohit  South  Printer  76200  61802
46       1047 2024-02-18   Suresh  North  Monitor  44240  38910
47       1048 2024-03-25     Neha   East   Laptop  19029  15655
48       1049 2023-05-25    Kiran  South   Tablet  31685  25546
49       1050 2023-09-16    Pooja   East   Laptop  17097  13511
50       1051 2023-01-23    Rahul   East   Mobile  39335  25507
51       1052 2023-12-28    Vikas  North   Laptop  14862  13130
52       1053 2023-03-18   Suresh  North   Tablet  77420  49891
53       1054 2023-06-07   Anjali  North   Tablet  32535  26178
54       1055 2023-07-01   Suresh   West  Monitor  25257  22168
55       1056 2023-03-25     Neha   West   Laptop  28509  23405
56       1057 2023-07-30    Priya   East   Mobile  19168  13700
57       1058        NaT    Pooja  South   Mobile  65332  46052
58       1059 2024-03-22    Priya  South   Laptop  30313  21811
59       1060 2023-02-05    Rohit   East  Monitor  57386  46130
60       1061 2023-06-19    Rahul  North   Tablet  28405  21990
61       1062 2023-01-20     Aman   West   Tablet  46114  33705
62       1063 2023-03-01    Vikas  South   Tablet  10817   8790
63       1064        NaT   Suresh  South   Tablet  61531  38210
64       1065 2023-06-19    Kiran   East   Laptop  44363  33367
65       1066 2023-06-17    Vikas   East  Monitor  21683  14257
66       1067 2023-07-14     Neha   East  Printer  76819  65305
67       1068 2023-04-18    Vikas   East  Printer  62905  46087
68       1069 2023-08-31     Neha  North   Tablet  72561  57987
69       1070 2023-02-17    Priya   East   Mobile  31100  20034
70       1071        NaT    Pooja  North  Printer  59321  51362
71       1072 2024-01-03    Vikas   West  Printer  36979  23824
72       1073 2024-01-20     Aman   West   Mobile  28053  23599
73       1074 2023-08-26    Rahul  South   Laptop  64829  41490
74       1075 2023-09-29   Suresh   East  Printer  71162  51807
75       1076 2023-08-17     Neha   West  Printer  38972  32172
76       1077 2023-05-22   Suresh   West   Mobile  40992  30004
77       1078 2023-05-01    Rohit   East   Tablet  75798  47311
78       1079 2023-07-16     Neha  South   Laptop  59377  42886
79       1080 2023-08-01    Rahul  South  Printer  56049  48843
80       1081 2023-12-23    Rahul   West  Printer   5772   5095
81       1082 2023-07-19    Vikas  South  Printer  33760  23020
82       1083 2023-07-19   Anjali   West   Mobile  66261  58035
83       1084 2023-10-01    Rahul   West  Monitor  78975  63093
84       1085 2023-08-08     Neha   West   Mobile  11590   7858
85       1086 2023-08-21   Anjali   East  Printer  41471  34238
86       1087 2023-05-10     Aman   West   Laptop  75702  46604
87       1088 2023-04-25     Aman  North   Laptop  37411  24684
88       1089        NaT     Neha  South   Mobile  67070  53712
89       1090 2023-04-22    Pooja   East   Tablet  26992  21101
90       1091 2024-01-03     Aman  South   Tablet  19168  14828
91       1092 2023-10-22    Vikas   West   Mobile  14961  11634
92       1093 2023-05-05     Aman   East  Monitor  20866  17503
93       1094 2023-01-22   Anjali   West   Tablet  14038  10553
94       1095 2024-03-10    Vikas   West   Laptop  61822  54912
95       1096 2024-02-29    Pooja  South  Printer  28086  23034
96       1097 2023-05-19    Kiran   West  Printer  62091  52635
97       1098 2023-06-15    Priya  North   Tablet  64087  43140
98       1099 2023-11-09    Vikas   East   Laptop  69789  59689
99       1100 2023-04-19   Anjali   East   Tablet  41655  35993
100      1101 2023-05-22   Suresh  North  Monitor  30042  18796
101      1102 2023-09-08   Suresh  South  Printer  69332  50921
102      1103        NaT    Rohit  South  Printer  36890  25522
103      1104 2023-08-31   Suresh   East  Printer  77140  53939
104      1105 2023-05-19    Rohit   East   Mobile  20814  16992
105      1106 2024-01-16   Suresh  South   Mobile  33361  27408
106      1107 2023-10-29   Suresh   East   Laptop  30443  20971
107      1108 2023-06-04    Rahul  South   Tablet  10965   9783
108      1109 2023-12-24     Neha   West   Laptop   6607   5102
109      1110 2023-08-14   Anjali  South   Laptop  38092  33609
110      1111 2024-02-25     Aman   West  Printer  14710  11372
111      1112 2023-03-19     Neha   East   Laptop  37530  23851
112      1113 2023-11-07    Kiran  South  Monitor  54856  40327
113      1114 2024-03-16    Kiran   West   Tablet  79531  62535
114      1115 2024-01-14     Aman  South   Mobile  39687  31675
115      1116 2023-03-30   Suresh  North   Mobile   5350   3865
116      1117 2023-08-29    Rohit  North   Mobile  42762  34726
117      1118 2023-08-21     Aman  South   Tablet  30928  22501
118      1119 2023-11-28     Neha   East   Mobile  14359   8872
119      1120 2023-11-01    Kiran   East  Printer  21299  15774
120      1121 2023-07-26    Rohit   West  Printer  15543  12114
121      1122 2024-01-12   Anjali   East   Laptop  16970  11347
122      1123 2024-03-16    Kiran  North   Tablet  10273   8515
123      1124 2023-09-23    Pooja   East   Mobile  62132  49111
124      1125 2023-02-16    Pooja   East  Printer  48687  33901
125      1126 2023-03-24   Anjali   West  Printer  42777  34169
126      1127 2024-01-25   Suresh  North  Printer  16542  11486
127      1128 2024-01-31    Vikas  North  Monitor  65552  47457
128      1129 2023-07-05    Kiran   West  Printer  11764   7776
129      1130 2023-05-28    Pooja   West   Laptop   8783   7833
130      1131 2023-05-03     Neha   East  Monitor   6792   5200
131      1132 2024-03-06     Aman   West   Laptop  25181  18873
132      1133 2023-09-18    Rohit   West  Printer  66894  45027
133      1134 2023-07-16    Priya  South   Laptop  41208  34276
134      1135 2023-06-24   Suresh   East   Laptop  42072  34407
135      1136 2023-10-24    Pooja  South  Printer  75592  56338
136      1137 2024-01-26   Suresh   West  Printer  47176  40612
137      1138 2023-05-03    Kiran   West   Mobile  58841  36075
138      1139 2023-12-28    Vikas   West   Mobile  69923  62192
139      1140 2023-10-30   Anjali  North  Printer  18069  13692
140      1141 2024-01-05     Neha   West   Mobile  14807  10969
141      1142 2023-06-23    Kiran   West   Laptop  48065  41129
142      1143 2023-07-14   Anjali   West  Monitor   9705   7620
143      1144 2023-12-17    Rohit  South   Laptop  61881  55290
144      1145 2023-12-27     Aman   West   Mobile  44251  38543
145      1146        NaT    Rahul   East   Tablet  54131  39472
146      1147 2023-07-30    Kiran  South   Mobile  27946  17429
147      1148 2023-11-14    Priya   West  Monitor  23758  15909
148      1149 2023-08-24    Rohit  North  Printer  42700  34300
149      1150 2023-08-15   Anjali   East  Printer  37780  27845
150      1151 2023-07-16    Pooja  North   Mobile  54986  42425
151      1152 2023-12-25    Rohit  North  Printer  40976  24685
152      1153 2024-02-03    Rahul   West   Tablet  35162  27500
153      1154 2023-11-22    Priya   East   Mobile  17735  15447
154      1155 2023-06-08    Pooja  North  Monitor  52823  43299
155      1156 2023-06-01   Anjali   West   Mobile  31318  20032
156      1157 2023-07-07   Suresh   East   Mobile  38681  33815
157      1158 2024-02-17    Rohit   East   Laptop  66385  59007
158      1159 2023-04-26    Vikas   East   Laptop  56717  34267
159      1160 2023-08-21   Anjali   East  Monitor  54941  46519
160      1161 2023-02-25    Priya   West   Laptop  78584  54883
161      1162 2023-11-28     Aman   West   Tablet  58516  37157
162      1163        NaT    Rahul   East  Printer  20220  12721
163      1164 2023-03-11    Vikas   West   Tablet  75804  55013
164      1165 2023-03-21    Vikas  North  Printer  58492  51573
165      1166 2023-12-20   Anjali  South  Printer  63287  56019
166      1167 2023-02-20   Anjali   East   Laptop  57184  39043
167      1168 2024-03-10    Pooja  North   Mobile   7799   4797
168      1169 2023-03-06    Kiran  South   Laptop  77641  51409
169      1170 2024-03-21    Priya   East   Mobile   5371   3669
170      1171 2023-03-08   Suresh   East   Mobile  19408  15493
171      1172        NaT    Rahul   East   Mobile  47437  28686
172      1173 2023-03-06    Vikas  North   Laptop  67422  49520
173      1174 2023-10-31     Aman   West  Monitor  34038  30076
174      1175        NaT   Suresh   East  Printer   9082   5614
175      1176 2023-07-25    Vikas  North  Printer  63138  39274
176      1177 2023-11-08     Neha  North   Mobile  41046  32315
177      1178 2023-12-31   Anjali   West  Monitor  74541  51319
178      1179 2023-08-09     Aman  North  Monitor  33183  24191
179      1180 2023-07-31   Anjali   West  Printer  59524  48743
180      1181 2023-06-10    Rohit   East   Mobile  67163  41650
181      1182 2023-02-17    Vikas  North   Tablet  22054  16913
182      1183 2023-10-15   Suresh   East   Laptop  58845  41549
183      1184 2024-01-20    Vikas  North   Tablet  45953  32419
184      1185 2023-04-19     Neha   West   Mobile  19184  13525
185      1186 2023-02-28    Rohit  South  Printer  78526  70073
186      1187 2023-11-11   Suresh  North  Monitor  40054  24380
187      1188 2024-01-26    Rohit   East   Tablet   5800   3795
188      1189 2023-12-03    Vikas  North   Mobile   9018   5659
189      1190 2023-07-12    Vikas   West   Tablet  25631  18224
190      1191 2024-02-02    Kiran  North   Laptop  25392  16434
191      1192 2023-12-12     Aman   East  Printer  60576  45171
192      1193 2023-05-20    Priya  North   Tablet  61349  38850
193      1194 2023-10-31    Pooja   East   Laptop  33903  24361
194      1195 2023-01-04    Priya   East   Mobile  22987  19061
195      1196 2023-03-03    Rahul   West  Printer  28028  17903
196      1197 2023-04-28   Suresh   East   Laptop  57044  48973
197      1198        NaT    Rahul   West   Laptop  46033  35570
198      1199 2023-12-30    Vikas   East   Laptop  58088  35216
199      1200 2024-02-15    Kiran   West   Tablet  16551  12099
200      1201 2023-08-12    Kiran   West  Monitor  15308  11002
201      1202 2023-06-23    Priya   East   Mobile  15011  11305
202      1203 2023-09-19    Priya   East   Tablet  24358  16341
203      1204 2023-04-12     Neha  South   Laptop  28218  24983
204      1205 2023-08-26    Kiran   West  Monitor  47363  40697
205      1206 2023-03-19    Pooja  North  Printer  62961  49702
206      1207 2023-10-30    Rahul   East  Monitor  14724  10205
207      1208 2023-01-30   Anjali   East   Laptop  16835  13207
208      1209 2023-08-25    Kiran  North  Printer  79928  63586
209      1210 2023-09-01   Suresh  South   Laptop  64050  40418
210      1211 2023-06-25     Aman  South   Laptop  37472  30438
211      1212 2023-09-26   Suresh  South   Tablet  53870  47156
212      1213 2024-02-01   Anjali  North   Tablet  13639   9532
213      1214 2023-07-17    Rohit   East  Monitor  24709  17296
214      1215 2023-03-14   Anjali   East  Printer  21901  17050
215      1216 2023-06-08   Suresh   West   Tablet  21750  17422
216      1217 2024-01-14   Suresh  North  Printer  71648  50766
217      1218 2023-04-03    Priya   East  Printer  30166  20149
218      1219 2023-02-09    Rohit  North  Monitor  75748  64426
219      1220 2023-01-20   Anjali  South  Monitor  54377  35142
220      1221 2023-12-21    Kiran  South  Printer  10726   7757
221      1222 2023-05-02    Pooja   East  Printer  35671  27117
222      1223 2024-02-19    Pooja  South   Tablet  79766  71417
223      1224 2023-05-25    Vikas   West   Mobile  31174  26197
224      1225 2023-05-09    Rahul   West   Tablet  77684  68384
225      1226 2023-09-22     Aman   East   Laptop  26012  17735
226      1227 2023-03-17    Vikas  North   Mobile  64130  55497
227      1228 2023-08-01    Rahul   West  Monitor  54015  36229
228      1229 2023-07-11    Priya  North   Tablet  17987  15320
229      1230 2024-02-10     Neha  South   Laptop  42601  37285
230      1231 2024-03-01     Neha   West  Printer   5688   4958
231      1232        NaT    Priya  South  Monitor  74176  53924
232      1233 2023-05-02    Rohit  North   Laptop  36252  26317
233      1234 2023-08-23     Aman  North  Printer  75261  45527
234      1235 2023-05-04     Neha   East  Printer   5205   4083
235      1236 2023-08-02     Neha  North  Monitor  52265  32420
236      1237 2023-09-17   Suresh  North  Printer  66621  40842
237      1238 2023-07-11    Rohit  North   Tablet  13855   9746
238      1239 2023-11-18     Aman   East   Mobile  10811   7629
239      1240 2023-11-26     Neha   West  Printer  28891  24368
240      1241 2024-02-02    Pooja  North   Tablet  31422  19266
241      1242 2023-01-22   Anjali   East  Monitor  57196  51289
242      1243 2023-05-10    Rahul  South   Tablet  51789  44468
243      1244        NaT   Anjali   East   Laptop  53237  38920
244      1245 2023-08-14    Vikas   East   Mobile  70038  56564
245      1246 2024-02-13   Suresh   East   Laptop  60640  37819
246      1247 2024-02-26     Neha   East   Tablet  18447  11511
247      1248 2023-06-06    Pooja   West   Mobile  63183  44573
248      1249        NaT   Anjali   West   Tablet  12518   7792
249      1250 2023-07-06   Suresh  South   Laptop  23714  20266
250      1251 2023-08-13    Rahul  South   Laptop  35932  29951
251      1252 2023-07-16    Kiran  North  Monitor  25111  20182
252      1253 2023-07-10    Pooja  North  Monitor  23047  17488
253      1254 2023-11-29    Rohit  South   Laptop   8396   6890
254      1255 2023-07-18   Suresh  North   Tablet  39116  31731
255      1256 2023-11-10    Rohit   West   Mobile  21074  13502
256      1257 2023-03-30    Pooja  North   Tablet  50537  41079
257      1258 2023-05-29    Rohit  South   Mobile  52381  39423
258      1259 2023-04-13     Neha  South  Printer   8445   5981
259      1260 2023-08-28   Suresh  South  Monitor  16300  10101
260      1261 2024-01-03    Pooja   West  Printer  14666   9351
261      1262 2023-02-07    Pooja   West  Monitor  50156  32024
262      1263 2023-10-10    Kiran  South   Mobile  61704  46331
263      1264 2024-03-01     Aman  South   Tablet  26581  17240
264      1265 2023-04-26   Anjali   East   Laptop  37847  24937
265      1266 2023-05-21     Neha   East  Monitor  74924  47054
266      1267 2023-10-31    Kiran  South   Mobile  49252  42000
267      1268 2024-02-27    Rahul  North   Laptop  39688  31565
268      1269 2023-08-02    Kiran  North  Printer  76509  52554
269      1270 2023-09-05    Priya   West   Tablet  64446  40078
270      1271 2023-08-14    Vikas   West  Printer  31741  22284
271      1272 2024-03-17   Anjali   East  Printer  22139  18335
272      1273 2023-02-24   Anjali  South  Printer  21059  14325
273      1274 2023-02-19    Rahul   East  Printer  59805  40337
274      1275 2023-03-23   Anjali   East   Mobile  25885  19400
275      1276 2023-09-13    Rohit   West   Laptop  16802  14845
276      1277 2023-05-04    Priya   East   Laptop  11624   7955
277      1278 2024-03-07    Pooja   East  Monitor   6071   5185
278      1279 2023-05-16   Anjali   West   Tablet  10930   7871
279      1280 2023-04-10   Anjali   East   Laptop  55639  41800
280      1281 2023-05-24    Kiran  North   Mobile  17672  12691
281      1282 2023-06-23   Suresh   East   Mobile  31090  24273
282      1283 2023-01-21    Rahul  North   Mobile  48652  40925
283      1284 2023-03-18    Kiran  South   Tablet  46750  30329
284      1285 2024-01-14    Rohit   East  Monitor  71809  54553
285      1286 2023-06-03    Pooja  North   Tablet  48416  38836
286      1287 2023-10-26    Rohit  North  Monitor  67205  45676
287      1288 2024-02-02    Kiran  South   Laptop  67973  44260
288      1289 2023-11-14    Vikas  South   Mobile   9138   7052
289      1290 2023-04-08    Rahul   West   Tablet  59890  38654
290      1291 2023-07-30   Suresh   West   Laptop  23098  17452
291      1292 2023-12-06    Pooja   West   Tablet  27699  20439
292      1293 2023-10-07   Anjali   East  Monitor  68462  45026
293      1294 2023-10-13    Rohit  South   Tablet  42880  34795
294      1295 2023-09-08   Anjali   West   Tablet  78464  69056
295      1296 2023-05-21    Rohit  North  Monitor  76197  54397
296      1297 2024-02-24   Anjali  South   Tablet  10513   7214
297      1298 2023-06-27    Pooja   East  Printer  33047  21831
298      1299 2023-10-15    Rohit  South   Laptop  36363  24462
299      1300 2023-09-29    Priya  South   Laptop  18133  13128
300      1301 2023-02-21     Neha  North  Monitor  25701  18557
301      1302 2024-03-25    Pooja   West   Mobile  42649  29698
302      1303 2024-01-29     Aman  South  Monitor   9888   8641
303      1304 2024-03-04     Neha  North  Printer  69930  45866
304      1305 2024-03-22    Rohit  North   Laptop  44110  33981
305      1306 2023-06-21    Rohit   West  Monitor  73723  55157
306      1307 2024-03-11   Suresh   West   Tablet  30272  25508
307      1308 2024-01-10    Pooja   East   Mobile   6846   5620
308      1309 2023-10-18    Priya  South  Monitor  58148  49315
309      1310 2023-02-14    Vikas  North   Mobile  23430  17414
310      1311 2023-01-04    Rohit   West   Mobile  63554  52503

In [25]:
# fix orderdate
df['Order_Date']=pd.to_datetime(df['Order_Date'],errors='coerce')

In [26]:
df.dropna(subset=['Order_Date'],inplace=True)

In [27]:
df["Profit"]=df['Sales']-df['Cost']
df['Year']=pd.to_datetime(df['Order_Date']).dt.year
df['Month']=df['Order_Date'].dt.month

In [28]:
df["Profit"]

0       4171
1       3312
2      20028
3      15705
4      20329
5      27295
6      11885
7       4974
8      17386
9      13017
10      4086
12      7653
13     18726
14      3402
15      5302
16     12173
17     13172
18      6790
19      2631
20      9249
21     12035
22      4996
23      7766
24      6693
25     14488
26     19415
27      4214
28     11455
29     10569
30     15304
31      7907
32     20800
33      6863
34      7452
35     21834
36     15681
37     29036
38     26322
39      2746
40      2187
41      6326
42     19813
43      7972
44      6889
45     14398
46      5330
47      3374
48      6139
49      3586
50     13828
51      1732
52     27529
53      6357
54      3089
55      5104
56      5468
58      8502
59     11256
60      6415
61     12409
62      2027
64     10996
65      7426
66     11514
67     16818
68     14574
69     11066
71     13155
72      4454
73     23339
74     19355
75      6800
76     10988
77     28487
78     16491
79      7206
80       677
81     10740
82      8226
83     15882
84      3732
85      7233
86     29098
87     12727
89      5891
90      4340
91      3327
92      3363
93      3485
94      6910
95      5052
96      9456
97     20947
98     10100
99      5662
100    11246
101    18411
103    23201
104     3822
105     5953
106     9472
107     1182
108     1505
109     4483
110     3338
111    13679
112    14529
113    16996
114     8012
115     1485
116     8036
117     8427
118     5487
119     5525
120     3429
121     5623
122     1758
123    13021
124    14786
125     8608
126     5056
127    18095
128     3988
129      950
130     1592
131     6308
132    21867
133     6932
134     7665
135    19254
136     6564
137    22766
138     7731
139     4377
140     3838
141     6936
142     2085
143     6591
144     5708
146    10517
147     7849
148     8400
149     9935
150    12561
151    16291
152     7662
153     2288
154     9524
155    11286
156     4866
157     7378
158    22450
159     8422
160    23701
161    21359
163    20791
164     6919
165     7268
166    18141
167     3002
168    26232
169     1702
170     3915
172    17902
173     3962
175    23864
176     8731
177    23222
178     8992
179    10781
180    25513
181     5141
182    17296
183    13534
184     5659
185     8453
186    15674
187     2005
188     3359
189     7407
190     8958
191    15405
192    22499
193     9542
194     3926
195    10125
196     8071
198    22872
199     4452
200     4306
201     3706
202     8017
203     3235
204     6666
205    13259
206     4519
207     3628
208    16342
209    23632
210     7034
211     6714
212     4107
213     7413
214     4851
215     4328
216    20882
217    10017
218    11322
219    19235
220     2969
221     8554
222     8349
223     4977
224     9300
225     8277
226     8633
227    17786
228     2667
229     5316
230      730
232     9935
233    29734
234     1122
235    19845
236    25779
237     4109
238     3182
239     4523
240    12156
241     5907
242     7321
244    13474
245    22821
246     6936
247    18610
249     3448
250     5981
251     4929
252     5559
253     1506
254     7385
255     7572
256     9458
257    12958
258     2464
259     6199
260     5315
261    18132
262    15373
263     9341
264    12910
265    27870
266     7252
267     8123
268    23955
269    24368
270     9457
271     3804
272     6734
273    19468
274     6485
275     1957
276     3669
277      886
278     3059
279    13839
280     4981
281     6817
282     7727
283    16421
284    17256
285     9580
286    21529
287    23713
288     2086
289    21236
290     5646
291     7260
292    23436
293     8085
294     9408
295    21800
296     3299
297    11216
298    11901
299     5005
300     7144
301    12951
302     1247
303    24064
304    10129
305    18566
306     4764
307     1226
308     8833
309     6016
310    11051
311    10018
312    11290
313    11465
314    14856
315     3813
316     9916
317    19578
318    19150
319    30198
320     5948
321     9525
322    11823
323     8875
324     7120
325      850
326     8371
327     7725
328     5110
330    14151
331     6110
332    15675
333    27001
334    20786
335    10699
336     6481
337     9525
338    11524
339     4705
340     4506
341     8517
342    23481
343    11475
344     9133
345     9169
346     9247
347    15897
348    17867
349     1399
350     3390
351    18763
352     2811
353    16812
354     4278
355     6467
356     8633
357    15694
358    10324
359     3502
360     1363
361    18271
362     6069
363     3802
364     4787
365     1864
366     9117
367     7020
368     4492
369    18483
370    14867
371    28890
372    16804
373     9753
374    19659
375     6857
376     7024
377    18784
378    10302
379    14638
380    17151
381    26477
382     6505
383    14632
384     6565
385     1599
386     7610
387     6310
388     5779
389    15274
390     2098
391    13631
392     4779
393     7898
394     6533
395    10039
396    17370
397     2937
398     6406
399    12640
400     3196
401    10353
402    15100
403    15340
404     1593
405    19121
406     1459
407    14973
408     6383
409    25622
410    20537
411     5098
412     3826
413     9245
414     4576
415     1306
416     7152
417     8514
418     7945
419      742
420    21065
421     7169
422     4382
423     6880
425     4559
426     9680
427     5481
428     7749
429     9981
430    15870
431    17219
432     3081
433     4070
434     7597
435    15070
436     9149
437      684
438    14949
439     5484
440    16226
441     4900
442     4195
443     1999
444    10205
445    12263
446     3788
447    19510
448    15957
449     8287
450     2064
451     6841
452    15358
453    19617
454     1254
455     3821
457    13171
458    22496
459     7893
460     7759
461     4623
462     4354
463     7281
464    20488
465     6610
466    19753
467     3451
468    14005
469    14989
470     8293
471    10442
472      793
473    17602
474    27392
475    12972
476    19456
477     6304
478      780
479    19729
480    13187
481     8812
482     9580
483    16414
484     7382
485    28187
486    26924
487    27047
488    18119
489     5908
490    13510
491     5229
492     8017
493     8155
494     5778
495     7046
496    13037
497     3524
499    12141
500    18271
501    23339
502    19659
503    11286
504     3822
505     6533
506    18784
507    14786
508    14574
509     2064
510    13017
511     3926
512     1459
513     3732
514    28890
515     5779
516     7046
517    15304
518     9916
519     6383
Name: Profit, dtype: int64

In [29]:
df["Year"]

0      2023
1      2023
2      2023
3      2024
4      2024
5      2023
6      2023
7      2023
8      2023
9      2023
10     2023
12     2024
13     2023
14     2023
15     2023
16     2023
17     2023
18     2023
19     2024
20     2023
21     2024
22     2023
23     2023
24     2023
25     2024
26     2023
27     2023
28     2024
29     2023
30     2023
31     2023
32     2023
33     2024
34     2024
35     2024
36     2024
37     2023
38     2023
39     2023
40     2023
41     2023
42     2023
43     2023
44     2023
45     2023
46     2024
47     2024
48     2023
49     2023
50     2023
51     2023
52     2023
53     2023
54     2023
55     2023
56     2023
58     2024
59     2023
60     2023
61     2023
62     2023
64     2023
65     2023
66     2023
67     2023
68     2023
69     2023
71     2024
72     2024
73     2023
74     2023
75     2023
76     2023
77     2023
78     2023
79     2023
80     2023
81     2023
82     2023
83     2023
84     2023
85     2023
86     2023
87     2023
89     2023
90     2024
91     2023
92     2023
93     2023
94     2024
95     2024
96     2023
97     2023
98     2023
99     2023
100    2023
101    2023
103    2023
104    2023
105    2024
106    2023
107    2023
108    2023
109    2023
110    2024
111    2023
112    2023
113    2024
114    2024
115    2023
116    2023
117    2023
118    2023
119    2023
120    2023
121    2024
122    2024
123    2023
124    2023
125    2023
126    2024
127    2024
128    2023
129    2023
130    2023
131    2024
132    2023
133    2023
134    2023
135    2023
136    2024
137    2023
138    2023
139    2023
140    2024
141    2023
142    2023
143    2023
144    2023
146    2023
147    2023
148    2023
149    2023
150    2023
151    2023
152    2024
153    2023
154    2023
155    2023
156    2023
157    2024
158    2023
159    2023
160    2023
161    2023
163    2023
164    2023
165    2023
166    2023
167    2024
168    2023
169    2024
170    2023
172    2023
173    2023
175    2023
176    2023
177    2023
178    2023
179    2023
180    2023
181    2023
182    2023
183    2024
184    2023
185    2023
186    2023
187    2024
188    2023
189    2023
190    2024
191    2023
192    2023
193    2023
194    2023
195    2023
196    2023
198    2023
199    2024
200    2023
201    2023
202    2023
203    2023
204    2023
205    2023
206    2023
207    2023
208    2023
209    2023
210    2023
211    2023
212    2024
213    2023
214    2023
215    2023
216    2024
217    2023
218    2023
219    2023
220    2023
221    2023
222    2024
223    2023
224    2023
225    2023
226    2023
227    2023
228    2023
229    2024
230    2024
232    2023
233    2023
234    2023
235    2023
236    2023
237    2023
238    2023
239    2023
240    2024
241    2023
242    2023
244    2023
245    2024
246    2024
247    2023
249    2023
250    2023
251    2023
252    2023
253    2023
254    2023
255    2023
256    2023
257    2023
258    2023
259    2023
260    2024
261    2023
262    2023
263    2024
264    2023
265    2023
266    2023
267    2024
268    2023
269    2023
270    2023
271    2024
272    2023
273    2023
274    2023
275    2023
276    2023
277    2024
278    2023
279    2023
280    2023
281    2023
282    2023
283    2023
284    2024
285    2023
286    2023
287    2024
288    2023
289    2023
290    2023
291    2023
292    2023
293    2023
294    2023
295    2023
296    2024
297    2023
298    2023
299    2023
300    2023
301    2024
302    2024
303    2024
304    2024
305    2023
306    2024
307    2024
308    2023
309    2023
310    2023
311    2023
312    2023
313    2023
314    2023
315    2023
316    2023
317    2023
318    2024
319    2023
320    2024
321    2023
322    2023
323    2024
324    2023
325    2023
326    2024
327    2023
328    2023
330    2023
331    2023
332    2023
333    2024
334    2023
335    2024
336    2024
337    2023
338    2023
339    2023
340    2023
341    2023
342    2023
343    2023
344    2023
345    2023
346    2024
347    2024
348    2024
349    2023
350    2024
351    2023
352    2023
353    2023
354    2023
355    2023
356    2023
357    2023
358    2023
359    2023
360    2023
361    2023
362    2023
363    2024
364    2023
365    2023
366    2023
367    2023
368    2023
369    2023
370    2023
371    2023
372    2023
373    2023
374    2023
375    2024
376    2023
377    2023
378    2024
379    2023
380    2023
381    2023
382    2023
383    2024
384    2024
385    2023
386    2024
387    2023
388    2024
389    2023
390    2023
391    2023
392    2023
393    2023
394    2023
395    2023
396    2023
397    2023
398    2023
399    2023
400    2024
401    2023
402    2023
403    2023
404    2023
405    2023
406    2023
407    2023
408    2024
409    2023
410    2024
411    2023
412    2023
413    2024
414    2023
415    2023
416    2023
417    2023
418    2023
419    2023
420    2023
421    2024
422    2023
423    2024
425    2023
426    2023
427    2023
428    2023
429    2023
430    2023
431    2024
432    2023
433    2023
434    2023
435    2023
436    2023
437    2023
438    2023
439    2024
440    2023
441    2023
442    2023
443    2024
444    2023
445    2023
446    2024
447    2024
448    2023
449    2024
450    2023
451    2023
452    2024
453    2023
454    2023
455    2023
457    2023
458    2023
459    2024
460    2023
461    2023
462    2023
463    2023
464    2023
465    2023
466    2023
467    2023
468    2023
469    2023
470    2023
471    2023
472    2023
473    2023
474    2023
475    2023
476    2023
477    2023
478    2024
479    2023
480    2023
481    2023
482    2023
483    2024
484    2024
485    2023
486    2024
487    2023
488    2023
489    2023
490    2023
491    2024
492    2023
493    2023
494    2023
495    2023
496    2023
497    2023
499    2023
500    2023
501    2023
502    2023
503    2023
504    2023
505    2023
506    2023
507    2023
508    2023
509    2023
510    2023
511    2023
512    2023
513    2023
514    2023
515    2024
516    2023
517    2023
518    2023
519    2024
Name: Year, dtype: int32

In [30]:
df["Month"]

0       1
1      10
2      11
3       2
4       1
5      11
6       2
7       1
8       8
9      12
10     11
12      3
13      3
14      8
15      9
16      8
17      5
18      6
19      3
20     11
21      2
22      7
23      2
24     10
25      1
26      3
27     10
28      3
29     10
30      2
31     12
32      4
33      3
34      3
35      3
36      2
37      4
38      1
39      2
40      3
41     10
42      5
43      2
44      4
45      7
46      2
47      3
48      5
49      9
50      1
51     12
52      3
53      6
54      7
55      3
56      7
58      3
59      2
60      6
61      1
62      3
64      6
65      6
66      7
67      4
68      8
69      2
71      1
72      1
73      8
74      9
75      8
76      5
77      5
78      7
79      8
80     12
81      7
82      7
83     10
84      8
85      8
86      5
87      4
89      4
90      1
91     10
92      5
93      1
94      3
95      2
96      5
97      6
98     11
99      4
100     5
101     9
103     8
104     5
105     1
106    10
107     6
108    12
109     8
110     2
111     3
112    11
113     3
114     1
115     3
116     8
117     8
118    11
119    11
120     7
121     1
122     3
123     9
124     2
125     3
126     1
127     1
128     7
129     5
130     5
131     3
132     9
133     7
134     6
135    10
136     1
137     5
138    12
139    10
140     1
141     6
142     7
143    12
144    12
146     7
147    11
148     8
149     8
150     7
151    12
152     2
153    11
154     6
155     6
156     7
157     2
158     4
159     8
160     2
161    11
163     3
164     3
165    12
166     2
167     3
168     3
169     3
170     3
172     3
173    10
175     7
176    11
177    12
178     8
179     7
180     6
181     2
182    10
183     1
184     4
185     2
186    11
187     1
188    12
189     7
190     2
191    12
192     5
193    10
194     1
195     3
196     4
198    12
199     2
200     8
201     6
202     9
203     4
204     8
205     3
206    10
207     1
208     8
209     9
210     6
211     9
212     2
213     7
214     3
215     6
216     1
217     4
218     2
219     1
220    12
221     5
222     2
223     5
224     5
225     9
226     3
227     8
228     7
229     2
230     3
232     5
233     8
234     5
235     8
236     9
237     7
238    11
239    11
240     2
241     1
242     5
244     8
245     2
246     2
247     6
249     7
250     8
251     7
252     7
253    11
254     7
255    11
256     3
257     5
258     4
259     8
260     1
261     2
262    10
263     3
264     4
265     5
266    10
267     2
268     8
269     9
270     8
271     3
272     2
273     2
274     3
275     9
276     5
277     3
278     5
279     4
280     5
281     6
282     1
283     3
284     1
285     6
286    10
287     2
288    11
289     4
290     7
291    12
292    10
293    10
294     9
295     5
296     2
297     6
298    10
299     9
300     2
301     3
302     1
303     3
304     3
305     6
306     3
307     1
308    10
309     2
310     1
311     6
312     3
313    12
314     3
315     8
316     7
317    10
318     1
319     3
320     2
321    10
322     1
323     1
324     7
325     9
326     1
327     6
328    11
330     4
331    10
332     9
333     3
334    11
335     1
336     2
337     3
338     8
339    11
340    12
341     1
342    12
343     8
344     8
345    10
346     1
347     3
348     1
349     9
350     2
351    12
352    11
353     1
354    12
355    11
356     7
357    12
358    11
359     6
360    12
361     5
362     3
363     3
364     2
365     6
366     8
367    12
368     2
369     2
370     3
371     2
372     6
373    10
374     9
375     2
376    11
377     6
378     3
379     9
380     9
381     7
382     1
383     3
384     1
385     7
386     2
387    11
388     2
389     9
390    10
391     2
392     9
393     6
394     2
395     8
396     7
397     4
398     7
399     9
400     3
401     5
402     8
403    10
404     8
405     7
406     9
407     1
408     1
409     7
410     1
411     2
412     6
413     2
414    12
415    12
416     3
417    12
418     2
419     8
420     2
421     2
422    10
423     3
425     5
426     3
427     2
428    12
429     8
430     2
431     1
432     3
433     8
434     7
435     5
436     4
437     9
438     3
439     1
440     1
441    11
442     4
443     3
444    11
445    12
446     1
447     1
448    12
449     3
450    10
451     5
452     3
453     6
454     1
455     8
457     7
458     1
459     3
460     2
461     3
462    12
463     7
464     6
465     4
466     7
467     3
468     3
469     5
470     2
471     4
472     2
473    11
474     1
475     3
476     1
477     2
478     2
479     7
480     4
481     5
482     3
483     1
484     3
485    10
486     3
487    11
488     4
489    12
490    12
491     1
492    11
493     5
494    10
495     4
496     6
497     5
499    10
500     5
501     8
502     9
503     6
504     5
505     2
506     6
507     2
508     8
509    10
510    12
511     1
512     9
513     8
514     2
515     2
516     4
517     2
518     7
519     1
Name: Month, dtype: int32

In [31]:
df.to_csv('salesdata_cleaned.csv',index=False)

In [32]:
import pandas as pd

In [33]:
pf=pd.read_csv("salesdata_cleaned.csv")

In [34]:
pf

     Order_ID  Order_Date Customer  ... Profit  Year  Month
0        1001  2023-01-13    Rohit  ...   4171  2023      1
1        1002  2023-10-07     Aman  ...   3312  2023     10
2        1003  2023-11-05    Rahul  ...  20028  2023     11
3        1004  2024-02-19    Rahul  ...  15705  2024      2
4        1005  2024-01-26   Anjali  ...  20329  2024      1
5        1006  2023-11-06    Rohit  ...  27295  2023     11
6        1007  2023-02-10   Suresh  ...  11885  2023      2
7        1008  2023-01-24    Priya  ...   4974  2023      1
8        1009  2023-08-21   Anjali  ...  17386  2023      8
9        1010  2023-12-16     Aman  ...  13017  2023     12
10       1011  2023-11-24   Suresh  ...   4086  2023     11
11       1013  2024-03-24   Anjali  ...   7653  2024      3
12       1014  2023-03-15    Rohit  ...  18726  2023      3
13       1015  2023-08-08    Kiran  ...   3402  2023      8
14       1016  2023-09-10     Aman  ...   5302  2023      9
15       1017  2023-08-05    Kiran  ...  12173  2023      8
16       1018  2023-05-09   Suresh  ...  13172  2023      5
17       1019  2023-06-24     Aman  ...   6790  2023      6
18       1020  2024-03-24    Rohit  ...   2631  2024      3
19       1021  2023-11-24   Suresh  ...   9249  2023     11
20       1022  2024-02-03   Suresh  ...  12035  2024      2
21       1023  2023-07-05    Rohit  ...   4996  2023      7
22       1024  2023-02-13    Pooja  ...   7766  2023      2
23       1025  2023-10-09     Neha  ...   6693  2023     10
24       1026  2024-01-22    Priya  ...  14488  2024      1
25       1027  2023-03-03    Priya  ...  19415  2023      3
26       1028  2023-10-29    Priya  ...   4214  2023     10
27       1029  2024-03-16   Anjali  ...  11455  2024      3
28       1030  2023-10-04     Neha  ...  10569  2023     10
29       1031  2023-02-19    Vikas  ...  15304  2023      2
30       1032  2023-12-11     Aman  ...   7907  2023     12
31       1033  2023-04-09    Priya  ...  20800  2023      4
32       1034  2024-03-23     Aman  ...   6863  2024      3
33       1035  2024-03-04    Rahul  ...   7452  2024      3
34       1036  2024-03-18    Vikas  ...  21834  2024      3
35       1037  2024-02-06    Pooja  ...  15681  2024      2
36       1038  2023-04-08    Rohit  ...  29036  2023      4
37       1039  2023-01-26    Kiran  ...  26322  2023      1
38       1040  2023-02-11     Neha  ...   2746  2023      2
39       1041  2023-03-03    Kiran  ...   2187  2023      3
40       1042  2023-10-26    Kiran  ...   6326  2023     10
41       1043  2023-05-16    Vikas  ...  19813  2023      5
42       1044  2023-02-07    Rahul  ...   7972  2023      2
43       1045  2023-04-20   Suresh  ...   6889  2023      4
44       1046  2023-07-09    Rohit  ...  14398  2023      7
45       1047  2024-02-18   Suresh  ...   5330  2024      2
46       1048  2024-03-25     Neha  ...   3374  2024      3
47       1049  2023-05-25    Kiran  ...   6139  2023      5
48       1050  2023-09-16    Pooja  ...   3586  2023      9
49       1051  2023-01-23    Rahul  ...  13828  2023      1
50       1052  2023-12-28    Vikas  ...   1732  2023     12
51       1053  2023-03-18   Suresh  ...  27529  2023      3
52       1054  2023-06-07   Anjali  ...   6357  2023      6
53       1055  2023-07-01   Suresh  ...   3089  2023      7
54       1056  2023-03-25     Neha  ...   5104  2023      3
55       1057  2023-07-30    Priya  ...   5468  2023      7
56       1059  2024-03-22    Priya  ...   8502  2024      3
57       1060  2023-02-05    Rohit  ...  11256  2023      2
58       1061  2023-06-19    Rahul  ...   6415  2023      6
59       1062  2023-01-20     Aman  ...  12409  2023      1
60       1063  2023-03-01    Vikas  ...   2027  2023      3
61       1065  2023-06-19    Kiran  ...  10996  2023      6
62       1066  2023-06-17    Vikas  ...   7426  2023      6
63       1067  2023-07-14     Neha  ...  11514  2023      7
64       1068  2023-04-18    Vikas  ...  16818  2023      4
65       1069  2023-08-31     Neha  ...  14574  2023      8
66       1070  2023-02-17    Priya  ...  11066  2023      2
67       1072  2024-01-03    Vikas  ...  13155  2024      1
68       1073  2024-01-20     Aman  ...   4454  2024      1
69       1074  2023-08-26    Rahul  ...  23339  2023      8
70       1075  2023-09-29   Suresh  ...  19355  2023      9
71       1076  2023-08-17     Neha  ...   6800  2023      8
72       1077  2023-05-22   Suresh  ...  10988  2023      5
73       1078  2023-05-01    Rohit  ...  28487  2023      5
74       1079  2023-07-16     Neha  ...  16491  2023      7
75       1080  2023-08-01    Rahul  ...   7206  2023      8
76       1081  2023-12-23    Rahul  ...    677  2023     12
77       1082  2023-07-19    Vikas  ...  10740  2023      7
78       1083  2023-07-19   Anjali  ...   8226  2023      7
79       1084  2023-10-01    Rahul  ...  15882  2023     10
80       1085  2023-08-08     Neha  ...   3732  2023      8
81       1086  2023-08-21   Anjali  ...   7233  2023      8
82       1087  2023-05-10     Aman  ...  29098  2023      5
83       1088  2023-04-25     Aman  ...  12727  2023      4
84       1090  2023-04-22    Pooja  ...   5891  2023      4
85       1091  2024-01-03     Aman  ...   4340  2024      1
86       1092  2023-10-22    Vikas  ...   3327  2023     10
87       1093  2023-05-05     Aman  ...   3363  2023      5
88       1094  2023-01-22   Anjali  ...   3485  2023      1
89       1095  2024-03-10    Vikas  ...   6910  2024      3
90       1096  2024-02-29    Pooja  ...   5052  2024      2
91       1097  2023-05-19    Kiran  ...   9456  2023      5
92       1098  2023-06-15    Priya  ...  20947  2023      6
93       1099  2023-11-09    Vikas  ...  10100  2023     11
94       1100  2023-04-19   Anjali  ...   5662  2023      4
95       1101  2023-05-22   Suresh  ...  11246  2023      5
96       1102  2023-09-08   Suresh  ...  18411  2023      9
97       1104  2023-08-31   Suresh  ...  23201  2023      8
98       1105  2023-05-19    Rohit  ...   3822  2023      5
99       1106  2024-01-16   Suresh  ...   5953  2024      1
100      1107  2023-10-29   Suresh  ...   9472  2023     10
101      1108  2023-06-04    Rahul  ...   1182  2023      6
102      1109  2023-12-24     Neha  ...   1505  2023     12
103      1110  2023-08-14   Anjali  ...   4483  2023      8
104      1111  2024-02-25     Aman  ...   3338  2024      2
105      1112  2023-03-19     Neha  ...  13679  2023      3
106      1113  2023-11-07    Kiran  ...  14529  2023     11
107      1114  2024-03-16    Kiran  ...  16996  2024      3
108      1115  2024-01-14     Aman  ...   8012  2024      1
109      1116  2023-03-30   Suresh  ...   1485  2023      3
110      1117  2023-08-29    Rohit  ...   8036  2023      8
111      1118  2023-08-21     Aman  ...   8427  2023      8
112      1119  2023-11-28     Neha  ...   5487  2023     11
113      1120  2023-11-01    Kiran  ...   5525  2023     11
114      1121  2023-07-26    Rohit  ...   3429  2023      7
115      1122  2024-01-12   Anjali  ...   5623  2024      1
116      1123  2024-03-16    Kiran  ...   1758  2024      3
117      1124  2023-09-23    Pooja  ...  13021  2023      9
118      1125  2023-02-16    Pooja  ...  14786  2023      2
119      1126  2023-03-24   Anjali  ...   8608  2023      3
120      1127  2024-01-25   Suresh  ...   5056  2024      1
121      1128  2024-01-31    Vikas  ...  18095  2024      1
122      1129  2023-07-05    Kiran  ...   3988  2023      7
123      1130  2023-05-28    Pooja  ...    950  2023      5
124      1131  2023-05-03     Neha  ...   1592  2023      5
125      1132  2024-03-06     Aman  ...   6308  2024      3
126      1133  2023-09-18    Rohit  ...  21867  2023      9
127      1134  2023-07-16    Priya  ...   6932  2023      7
128      1135  2023-06-24   Suresh  ...   7665  2023      6
129      1136  2023-10-24    Pooja  ...  19254  2023     10
130      1137  2024-01-26   Suresh  ...   6564  2024      1
131      1138  2023-05-03    Kiran  ...  22766  2023      5
132      1139  2023-12-28    Vikas  ...   7731  2023     12
133      1140  2023-10-30   Anjali  ...   4377  2023     10
134      1141  2024-01-05     Neha  ...   3838  2024      1
135      1142  2023-06-23    Kiran  ...   6936  2023      6
136      1143  2023-07-14   Anjali  ...   2085  2023      7
137      1144  2023-12-17    Rohit  ...   6591  2023     12
138      1145  2023-12-27     Aman  ...   5708  2023     12
139      1147  2023-07-30    Kiran  ...  10517  2023      7
140      1148  2023-11-14    Priya  ...   7849  2023     11
141      1149  2023-08-24    Rohit  ...   8400  2023      8
142      1150  2023-08-15   Anjali  ...   9935  2023      8
143      1151  2023-07-16    Pooja  ...  12561  2023      7
144      1152  2023-12-25    Rohit  ...  16291  2023     12
145      1153  2024-02-03    Rahul  ...   7662  2024      2
146      1154  2023-11-22    Priya  ...   2288  2023     11
147      1155  2023-06-08    Pooja  ...   9524  2023      6
148      1156  2023-06-01   Anjali  ...  11286  2023      6
149      1157  2023-07-07   Suresh  ...   4866  2023      7
150      1158  2024-02-17    Rohit  ...   7378  2024      2
151      1159  2023-04-26    Vikas  ...  22450  2023      4
152      1160  2023-08-21   Anjali  ...   8422  2023      8
153      1161  2023-02-25    Priya  ...  23701  2023      2
154      1162  2023-11-28     Aman  ...  21359  2023     11
155      1164  2023-03-11    Vikas  ...  20791  2023      3
156      1165  2023-03-21    Vikas  ...   6919  2023      3
157      1166  2023-12-20   Anjali  ...   7268  2023     12
158      1167  2023-02-20   Anjali  ...  18141  2023      2
159      1168  2024-03-10    Pooja  ...   3002  2024      3
160      1169  2023-03-06    Kiran  ...  26232  2023      3
161      1170  2024-03-21    Priya  ...   1702  2024      3
162      1171  2023-03-08   Suresh  ...   3915  2023      3
163      1173  2023-03-06    Vikas  ...  17902  2023      3
164      1174  2023-10-31     Aman  ...   3962  2023     10
165      1176  2023-07-25    Vikas  ...  23864  2023      7
166      1177  2023-11-08     Neha  ...   8731  2023     11
167      1178  2023-12-31   Anjali  ...  23222  2023     12
168      1179  2023-08-09     Aman  ...   8992  2023      8
169      1180  2023-07-31   Anjali  ...  10781  2023      7
170      1181  2023-06-10    Rohit  ...  25513  2023      6
171      1182  2023-02-17    Vikas  ...   5141  2023      2
172      1183  2023-10-15   Suresh  ...  17296  2023     10
173      1184  2024-01-20    Vikas  ...  13534  2024      1
174      1185  2023-04-19     Neha  ...   5659  2023      4
175      1186  2023-02-28    Rohit  ...   8453  2023      2
176      1187  2023-11-11   Suresh  ...  15674  2023     11
177      1188  2024-01-26    Rohit  ...   2005  2024      1
178      1189  2023-12-03    Vikas  ...   3359  2023     12
179      1190  2023-07-12    Vikas  ...   7407  2023      7
180      1191  2024-02-02    Kiran  ...   8958  2024      2
181      1192  2023-12-12     Aman  ...  15405  2023     12
182      1193  2023-05-20    Priya  ...  22499  2023      5
183      1194  2023-10-31    Pooja  ...   9542  2023     10
184      1195  2023-01-04    Priya  ...   3926  2023      1
185      1196  2023-03-03    Rahul  ...  10125  2023      3
186      1197  2023-04-28   Suresh  ...   8071  2023      4
187      1199  2023-12-30    Vikas  ...  22872  2023     12
188      1200  2024-02-15    Kiran  ...   4452  2024      2
189      1201  2023-08-12    Kiran  ...   4306  2023      8
190      1202  2023-06-23    Priya  ...   3706  2023      6
191      1203  2023-09-19    Priya  ...   8017  2023      9
192      1204  2023-04-12     Neha  ...   3235  2023      4
193      1205  2023-08-26    Kiran  ...   6666  2023      8
194      1206  2023-03-19    Pooja  ...  13259  2023      3
195      1207  2023-10-30    Rahul  ...   4519  2023     10
196      1208  2023-01-30   Anjali  ...   3628  2023      1
197      1209  2023-08-25    Kiran  ...  16342  2023      8
198      1210  2023-09-01   Suresh  ...  23632  2023      9
199      1211  2023-06-25     Aman  ...   7034  2023      6
200      1212  2023-09-26   Suresh  ...   6714  2023      9
201      1213  2024-02-01   Anjali  ...   4107  2024      2
202      1214  2023-07-17    Rohit  ...   7413  2023      7
203      1215  2023-03-14   Anjali  ...   4851  2023      3
204      1216  2023-06-08   Suresh  ...   4328  2023      6
205      1217  2024-01-14   Suresh  ...  20882  2024      1
206      1218  2023-04-03    Priya  ...  10017  2023      4
207      1219  2023-02-09    Rohit  ...  11322  2023      2
208      1220  2023-01-20   Anjali  ...  19235  2023      1
209      1221  2023-12-21    Kiran  ...   2969  2023     12
210      1222  2023-05-02    Pooja  ...   8554  2023      5
211      1223  2024-02-19    Pooja  ...   8349  2024      2
212      1224  2023-05-25    Vikas  ...   4977  2023      5
213      1225  2023-05-09    Rahul  ...   9300  2023      5
214      1226  2023-09-22     Aman  ...   8277  2023      9
215      1227  2023-03-17    Vikas  ...   8633  2023      3
216      1228  2023-08-01    Rahul  ...  17786  2023      8
217      1229  2023-07-11    Priya  ...   2667  2023      7
218      1230  2024-02-10     Neha  ...   5316  2024      2
219      1231  2024-03-01     Neha  ...    730  2024      3
220      1233  2023-05-02    Rohit  ...   9935  2023      5
221      1234  2023-08-23     Aman  ...  29734  2023      8
222      1235  2023-05-04     Neha  ...   1122  2023      5
223      1236  2023-08-02     Neha  ...  19845  2023      8
224      1237  2023-09-17   Suresh  ...  25779  2023      9
225      1238  2023-07-11    Rohit  ...   4109  2023      7
226      1239  2023-11-18     Aman  ...   3182  2023     11
227      1240  2023-11-26     Neha  ...   4523  2023     11
228      1241  2024-02-02    Pooja  ...  12156  2024      2
229      1242  2023-01-22   Anjali  ...   5907  2023      1
230      1243  2023-05-10    Rahul  ...   7321  2023      5
231      1245  2023-08-14    Vikas  ...  13474  2023      8
232      1246  2024-02-13   Suresh  ...  22821  2024      2
233      1247  2024-02-26     Neha  ...   6936  2024      2
234      1248  2023-06-06    Pooja  ...  18610  2023      6
235      1250  2023-07-06   Suresh  ...   3448  2023      7
236      1251  2023-08-13    Rahul  ...   5981  2023      8
237      1252  2023-07-16    Kiran  ...   4929  2023      7
238      1253  2023-07-10    Pooja  ...   5559  2023      7
239      1254  2023-11-29    Rohit  ...   1506  2023     11
240      1255  2023-07-18   Suresh  ...   7385  2023      7
241      1256  2023-11-10    Rohit  ...   7572  2023     11
242      1257  2023-03-30    Pooja  ...   9458  2023      3
243      1258  2023-05-29    Rohit  ...  12958  2023      5
244      1259  2023-04-13     Neha  ...   2464  2023      4
245      1260  2023-08-28   Suresh  ...   6199  2023      8
246      1261  2024-01-03    Pooja  ...   5315  2024      1
247      1262  2023-02-07    Pooja  ...  18132  2023      2
248      1263  2023-10-10    Kiran  ...  15373  2023     10
249      1264  2024-03-01     Aman  ...   9341  2024      3
250      1265  2023-04-26   Anjali  ...  12910  2023      4
251      1266  2023-05-21     Neha  ...  27870  2023      5
252      1267  2023-10-31    Kiran  ...   7252  2023     10
253      1268  2024-02-27    Rahul  ...   8123  2024      2
254      1269  2023-08-02    Kiran  ...  23955  2023      8
255      1270  2023-09-05    Priya  ...  24368  2023      9
256      1271  2023-08-14    Vikas  ...   9457  2023      8
257      1272  2024-03-17   Anjali  ...   3804  2024      3
258      1273  2023-02-24   Anjali  ...   6734  2023      2
259      1274  2023-02-19    Rahul  ...  19468  2023      2
260      1275  2023-03-23   Anjali  ...   6485  2023      3
261      1276  2023-09-13    Rohit  ...   1957  2023      9
262      1277  2023-05-04    Priya  ...   3669  2023      5
263      1278  2024-03-07    Pooja  ...    886  2024      3
264      1279  2023-05-16   Anjali  ...   3059  2023      5
265      1280  2023-04-10   Anjali  ...  13839  2023      4
266      1281  2023-05-24    Kiran  ...   4981  2023      5
267      1282  2023-06-23   Suresh  ...   6817  2023      6
268      1283  2023-01-21    Rahul  ...   7727  2023      1
269      1284  2023-03-18    Kiran  ...  16421  2023      3
270      1285  2024-01-14    Rohit  ...  17256  2024      1
271      1286  2023-06-03    Pooja  ...   9580  2023      6
272      1287  2023-10-26    Rohit  ...  21529  2023     10
273      1288  2024-02-02    Kiran  ...  23713  2024      2
274      1289  2023-11-14    Vikas  ...   2086  2023     11
275      1290  2023-04-08    Rahul  ...  21236  2023      4
276      1291  2023-07-30   Suresh  ...   5646  2023      7
277      1292  2023-12-06    Pooja  ...   7260  2023     12
278      1293  2023-10-07   Anjali  ...  23436  2023     10
279      1294  2023-10-13    Rohit  ...   8085  2023     10
280      1295  2023-09-08   Anjali  ...   9408  2023      9
281      1296  2023-05-21    Rohit  ...  21800  2023      5
282      1297  2024-02-24   Anjali  ...   3299  2024      2
283      1298  2023-06-27    Pooja  ...  11216  2023      6
284      1299  2023-10-15    Rohit  ...  11901  2023     10
285      1300  2023-09-29    Priya  ...   5005  2023      9
286      1301  2023-02-21     Neha  ...   7144  2023      2
287      1302  2024-03-25    Pooja  ...  12951  2024      3
288      1303  2024-01-29     Aman  ...   1247  2024      1
289      1304  2024-03-04     Neha  ...  24064  2024      3
290      1305  2024-03-22    Rohit  ...  10129  2024      3
291      1306  2023-06-21    Rohit  ...  18566  2023      6
292      1307  2024-03-11   Suresh  ...   4764  2024      3
293      1308  2024-01-10    Pooja  ...   1226  2024      1
294      1309  2023-10-18    Priya  ...   8833  2023     10
295      1310  2023-02-14    Vikas  ...   6016  2023      2
296      1311  2023-01-04    Rohit  ...  11051  2023      1
297      1312  2023-06-04    Kiran  ...  10018  2023      6
298      1313  2023-03-02    Pooja  ...  11290  2023      3
299      1314  2023-12-27    Rohit  ...  11465  2023     12
300      1315  2023-03-10    Pooja  ...  14856  2023      3
301      1316  2023-08-30   Suresh  ...   3813  2023      8
302      1317  2023-07-05     Aman  ...   9916  2023      7
303      1318  2023-10-02     Neha  ...  19578  2023     10
304      1319  2024-01-03    Kiran  ...  19150  2024      1
305      1320  2023-03-09   Suresh  ...  30198  2023      3
306      1321  2024-02-18    Rohit  ...   5948  2024      2
307      1322  2023-10-24     Aman  ...   9525  2023     10
308      1323  2023-01-31     Aman  ...  11823  2023      1
309      1324  2024-01-28    Vikas  ...   8875  2024      1
310      1325  2023-07-12     Aman  ...   7120  2023      7
311      1326  2023-09-28     Neha  ...    850  2023      9
312      1327  2024-01-04   Suresh  ...   8371  2024      1
313      1328  2023-06-27     Neha  ...   7725  2023      6
314      1329  2023-11-11    Rahul  ...   5110  2023     11
315      1331  2023-04-22    Rahul  ...  14151  2023      4
316      1332  2023-10-22   Anjali  ...   6110  2023     10
317      1333  2023-09-24    Priya  ...  15675  2023      9
318      1334  2024-03-26     Neha  ...  27001  2024      3
319      1335  2023-11-26    Vikas  ...  20786  2023     11
320      1336  2024-01-22   Suresh  ...  10699  2024      1
321      1337  2024-02-17    Pooja  ...   6481  2024      2
322      1338  2023-03-10    Vikas  ...   9525  2023      3
323      1339  2023-08-19   Anjali  ...  11524  2023      8
324      1340  2023-11-06    Kiran  ...   4705  2023     11
325      1341  2023-12-10   Suresh  ...   4506  2023     12
326      1342  2023-01-08    Priya  ...   8517  2023      1
327      1343  2023-12-27    Priya  ...  23481  2023     12
328      1344  2023-08-27   Suresh  ...  11475  2023      8
329      1345  2023-08-27     Aman  ...   9133  2023      8
330      1346  2023-10-16    Priya  ...   9169  2023     10
331      1347  2024-01-04    Vikas  ...   9247  2024      1

In [35]:
from sqlalchemy import create_engine

In [37]:
username="root"
password=""
host="localhost"
port=3307
database="salesdb"

engine=create_engine(f"mysql+pymysql://{username}:{password}@{host}:{port}/{database}")
table_name="Sale_info"
df.to_sql(table_name,engine,if_exists='replace',index=False)

C:\Users\Naveed Sultan\AppData\Local\Temp\ipykernel_15952\1433324135.py:9: UserWarning: The provided table name 'Sale_info' is not found exactly as such in the database after writing the table, possibly due to case sensitivity issues. Consider using lower case table names.
  df.to_sql(table_name,engine,if_exists='replace',index=False)

502